config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :states

  match '*any' => 'application#options', :via => [:options]
  resources :bugs

  devise_for :users

  root 'bugs#index'

end

app/models/bug.rb
class Bug < ActiveRecord::Base
  belongs_to :state
  belongs_to :project

  validates :name, :project_id, :state_id,
            :presence => true
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
  before_filter :authenticate_or_token

  def options
    head :status => 200, :'Access-Control-Allow-Headers' => 'accept, content-type'
  end

private

  def authenticate_or_token
    if params[:api_key] == "6a4f2c952b3ccbc8924b89b7f5c3d0dc"
      @current_user = User.first
      return current_user
    end
    authenticate_user!
  end

end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, only: [:show, :edit, :update, :destroy]
  protect_from_forgery unless: -> { request.format.json? }
  before_filter :cors_set_access_control_headers

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = '*'
    headers['Access-Control-Allow-Headers'] = '*'
    headers['Access-Control-Request-Method'] = '*'
  end

  respond_to :html, :json

  def index
    @bugs = Bug.all

    respond_to do |format|
      format.html { respond_with(@bugs) }
      format.json {
        render json: @bugs, :callback => 'callback'
      }
    end

  end

  def show
    respond_with(@bug)
  end

  def new
    @bug = Bug.new
    respond_with(@bug)
  end

  def edit
  end

  def create
    @bug = Bug.new(bug_params)
    @bug.save
    respond_with(@bug)
  end

  def update
    @bug.update(bug_params)
    respond_with(@bug)
  end

  def destroy
    @bug.destroy
    respond_with(@bug)
  end

  private
    def set_bug
      @bug = Bug.find(params[:id])
    end

    def bug_params
      params.require(:bug).permit(:name, :description, :project_id, :state_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @projects = Project.all
    respond_with(@projects)
  end

  def show
    respond_with(@project)
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.save
    respond_with(@project)
  end

  def update
    @project.update(project_params)
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @states = State.all
    respond_with(@states)
  end

  def show
    respond_with(@state)
  end

  def new
    @state = State.new
    respond_with(@state)
  end

  def edit
  end

  def create
    @state = State.new(state_params)
    @state.save
    respond_with(@state)
  end

  def update
    @state.update(state_params)
    respond_with(@state)
  end

  def destroy
    @state.destroy
    respond_with(@state)
  end

  private
    def set_state
      @state = State.find(params[:id])
    end

    def state_params
      params.require(:state).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/bugs/_form.html.slim
= simple_form_for @bug do |f|
  = f.input :name, label: t('activerecord.attributes.bug.name')
  = f.input :description, label: t('activerecord.attributes.bug.description')
  = f.association :project, label: t('activerecord.attributes.bug.project_id')
  = f.association :state, label: t('activerecord.attributes.bug.state_id'), default: 1
  = f.button :submit
  = link_to 'Back', bugs_path

app/views/bugs/edit.html.slim
h1 Editing Bug

= render 'form'

app/views/bugs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bugs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Project</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
      <tr>
        <td><%= bug.name %></td>
        <td><%= bug.description %></td>
        <td><%= bug.project_id %></td>
        <td><%= bug.state_id %></td>
        <td><%= link_to 'Show', bug %></td>
        <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
        <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bug', new_bug_path %>

app/views/bugs/new.html.slim
h1 New Bug

= render 'form'

app/views/bugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bug.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bug.description %>
</p>

<p>
  <strong>Project:</strong>
  <%= @bug.project_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @bug.state_id %>
</p>

<%= link_to 'Edit', edit_bug_path(@bug) %> |
<%= link_to 'Back', bugs_path %>

app/views/layouts/application.html.slim
doctype 5
html lang='en'
head
  title Bugtracker
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

body
  = yield

app/views/projects/_form.html.slim
= simple_form_for @project do |f|
  = f.input :name, label: t('activerecord.attributes.project.name')
  = f.button :submit

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.slim
h1 Listing Projects

table
  thead
    tr
      th Name
      th colspan='2'
  tbody
    - @projects.each do |project|
      tr
        td = link_to project.name, project
        td = link_to 'Edit', edit_project_path(project)
        td = link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }

br

= link_to 'New Project', new_project_path

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing States</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.name %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>